---
title: "Counting cell change between different scenarios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(here)
library(tidyverse)
library(janitor)
library(stars)
```
```{r}
# # read in raster for 2020

scenario_raster_scenario1_2020 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1050_0.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2020 <- st_as_sf(scenario_raster_scenario1_2020[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2020) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2020) <- c("gridcode", "geometry")
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1050_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

difference_df <- data.frame(nrow(different_cells))
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1052_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)
#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_df, difference_df_2)
```
```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1053_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1054_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1057_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210825_1257_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210825_1259_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210825_1302_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```
```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210825_1304_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210825_1446_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210825_1448_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210826_1934_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210826_1935_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210826_1951_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210826_1957_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210826_1958_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210826_2000_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210827_1747_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```


# This is has the most cell differences
```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210827_1748_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)

max_difference <- difference_df_2
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210828_1644_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210828_1646_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210828_1648_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210820_1301_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210820_1302_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210820_1303_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210820_1306_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210820_1308_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210820_1309_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210821_1212_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210821_1213_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210821_1214_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210821_1215_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210821_1217_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210821_1218_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210821_1219_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```
# This is the minimum difference
```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210822_2122_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)

min_difference <- difference_df_2
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210822_2123_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210822_2124_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210822_2125_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210822_2127_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210822_2128_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210827_1746_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210828_1645_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210828_1646_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)
```

```{r}
#read in raster for 2040
scenario_raster_scenario1_2040 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210828_1648_20.tif"))

#vectorize raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2040 <- st_as_sf(scenario_raster_scenario1_2040[1], merge = FALSE, as_points = F)
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2040) <- 3717
#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2040) <- c("gridcode", "geometry")

#take the difference between the two 
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference) 
#find the number of cells that have changed
different_cells <- difference_dataframe %>% 
  filter(difference > 0)

#add to the dataframe that started with difference_df
difference_df_2 <- nrow(different_cells)
  
difference_new <- rbind(difference_new, difference_df_2)

#rename columns of difference_new
colnames(difference_new) <- c("cell_difference")
```





